### ISSUE TITLE
J-meter

### ISSUE THREAD

**Issue by jayashreebai** [zysk/testing-doc#1]
@RachayyaC Please continue the task here, add description of what are you achieving in this task and please mention the estimate time for this also mention the attachment

**Comment by RachayyaC** [comment]
1. Explore the Jmeter tool and prepare PPT.
2.J-meter tool is used for performance testing of the websites we can perform the load testing, stress testing.
3. We can monitor the behavior of the website under normal and abnormal load conditions.
4. stress testing is used to determine the limit at which the system/software/hardware breaks.

**Comment by jayashreebai** [comment]
@RachayyaC please comment before standup call.

**Comment by RachayyaC** [comment]
Here is the PPT of the Jmeter tool
https://show.zoho.com/show/open/lfc28aa66bc48e8e348bd9a2491460cb2facf/slide/6379b1db-7aac-49a4-8aca-0f56e9749b43

**Comment by RachayyaC** [comment]
Task completed
